In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# Specify encoding to handle non-UTF characters (commonly 'ISO-8859-1' or 'latin1')
df_movie = pd.read_csv(r'C:\Users\KIIT0001\Downloads\IMDb Movies India.csv', encoding='ISO-8859-1')

# Drop missing values
df_movie.dropna(inplace=True)

# Display first few rows
df_movie.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [11]:

df_movie.shape

(5659, 10)

In [12]:
df_movie.describe()

            Rating
count  5659.000000
mean      5.898533
std       1.381165
min       1.100000
25%       5.000000
50%       6.100000
75%       6.900000
max      10.000000

In [13]:

df_movie.isna().sum()

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [16]:
# Use the correct file path and specify encoding to handle non-UTF characters
df_ratings = pd.read_csv(r'C:\Users\KIIT0001\Downloads\IMDb Movies India.csv', sep="::", engine="python", encoding='ISO-8859-1')

# Drop rows with missing values
df_ratings.dropna(inplace=True)

# Display the first 10 rows
df_ratings.head(10)

  Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0  ,,,Drama,,,J.S. Randhawa,Manmauji,Birbal,Rajen...
1  #Gadhvi (He thought he was Gandhi),(2019),109 ...
2  #Homecoming,(2021),90 min,"Drama, Musical",,,S...
3  #Yaaram,(2019),110 min,"Comedy, Romance",4.4,3...
4  ...And Once Again,(2010),105 min,Drama,,,Amol ...
5  ...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, D...
6  ...Yahaan,(2005),142 min,"Drama, Romance, War"...
7  .in for Motion,(2008),59 min,Documentary,,,Ani...
8  ?: A Question Mark,(2012),82 min,"Horror, Myst...
9  @Andheri,(2014),116 min,"Action, Crime, Thrill...

In [17]:

df_ratings.shape

(15509, 1)

In [18]:
df_ratings.describe()

       Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
count                                               15509
unique                                              15503
top     Shivani,(2019),,Crime,,,Ugresh Prasad Ujala,Sa...
freq                                                    2

In [19]:
df_ratings.isna().sum()

Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3    0
dtype: int64

In [22]:
# Ensure the file path is correct
df_users = pd.read_csv(r'C:\Users\KIIT0001\Downloads\IMDb Movies India.csv', sep="::", engine="python", encoding='ISO-8859-1')

# Drop rows with missing values
df_users.dropna(inplace=True)

# Display the first 10 rows
df_users.head(10)

  Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0  ,,,Drama,,,J.S. Randhawa,Manmauji,Birbal,Rajen...
1  #Gadhvi (He thought he was Gandhi),(2019),109 ...
2  #Homecoming,(2021),90 min,"Drama, Musical",,,S...
3  #Yaaram,(2019),110 min,"Comedy, Romance",4.4,3...
4  ...And Once Again,(2010),105 min,Drama,,,Amol ...
5  ...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, D...
6  ...Yahaan,(2005),142 min,"Drama, Romance, War"...
7  .in for Motion,(2008),59 min,Documentary,,,Ani...
8  ?: A Question Mark,(2012),82 min,"Horror, Myst...
9  @Andheri,(2014),116 min,"Action, Crime, Thrill...

In [23]:

df_users.shape

(15509, 1)

In [24]:
df_users.describe()

       Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
count                                               15509
unique                                              15503
top     Shivani,(2019),,Crime,,,Ugresh Prasad Ujala,Sa...
freq                                                    2

In [26]:
from sklearn.preprocessing import LabelEncoder

# Ensure column names are clean
df_users.columns = df_users.columns.str.strip()

# Check if the 'Gender' column exists
print(df_users.columns)

# Proceed with label encoding if 'Gender' column exists
if 'Gender' in df_users.columns:
    labelencoder = LabelEncoder()
    df_users['Gender'] = labelencoder.fit_transform(df_users['Gender'])
    print(df_users.head())
else:
    print("The 'Gender' column is not found.")

Index(['Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3'], dtype='object')
The 'Gender' column is not found.

In [27]:
df_users.isna().sum()

Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3    0
dtype: int64

In [28]:
df_data=pd.concat([df_movie,df_ratings,df_users],axis=1)
df_data.dropna()
df_data.head(10)

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,"Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3","Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3"
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,"#Gadhvi (He thought he was Gandhi),(2019),109 ...","#Gadhvi (He thought he was Gandhi),(2019),109 ..."
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,"#Yaaram,(2019),110 min,""Comedy, Romance"",4.4,3...","#Yaaram,(2019),110 min,""Comedy, Romance"",4.4,3..."
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,"...Aur Pyaar Ho Gaya,(1997),147 min,""Comedy, D...","...Aur Pyaar Ho Gaya,(1997),147 min,""Comedy, D..."
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,"...Yahaan,(2005),142 min,""Drama, Romance, War""...","...Yahaan,(2005),142 min,""Drama, Romance, War""..."
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,"?: A Question Mark,(2012),82 min,""Horror, Myst...","?: A Question Mark,(2012),82 min,""Horror, Myst..."
9,@Andheri,(2014),116 min,"Action, Crime, Thriller",4.0,11,Biju Bhaskar Nair,Augustine,Fathima Babu,Byon,"@Andheri,(2014),116 min,""Action, Crime, Thrill...","@Andheri,(2014),116 min,""Action, Crime, Thrill..."
10,1:1.6 An Ode to Lost Love,(2004),96 min,Drama,6.2,17,Madhu Ambat,Rati Agnihotri,Gulshan Grover,Atul Kulkarni,"1:1.6 An Ode to Lost Love,(2004),96 min,Drama,...","1:1.6 An Ode to Lost Love,(2004),96 min,Drama,..."
11,1:13:7 Ek Tera Saath,(2016),120 min,Horror,5.9,59,Arshad Siddiqui,Pankaj Berry,Anubhav Dhir,Hritu Dudani,"1:13:7 Ek Tera Saath,(2016),120 min,Horror,5.9...","1:13:7 Ek Tera Saath,(2016),120 min,Horror,5.9..."
12,100 Days,(1991),161 min,"Horror, Romance, Thriller",6.5,983,Partho Ghosh,Jackie Shroff,Madhuri Dixit,Javed Jaffrey,"100 Days,(1991),161 min,""Horror, Romance, Thri...","100 Days,(1991),161 min,""Horror, Romance, Thri..."
13,100% Love,(2012),166 min,"Comedy, Drama, Romance",5.7,512,Rabi Kinagi,Jeet,Koyel Mallick,Sujoy Ghosh,"100% Love,(2012),166 min,""Comedy, Drama, Roman...","100% Love,(2012),166 min,""Comedy, Drama, Roman..."

In [29]:
df_data.shape

(15509, 12)

In [31]:
# Ensure column names are clean
df_data.columns = df_data.columns.str.strip()

# Check the columns to verify if they exist
print(df_data.columns)

# Drop columns if they exist, ignore missing ones
df2 = df_data.drop(["Occupation", "Zip-code", "Timestamp"], axis=1, errors='ignore')

# Display the first few rows of the updated DataFrame
print(df2.head())

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3'],
      dtype='object')
                                 Name    Year Duration  \
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min
3                             #Yaaram  (2019)  110 min
5                ...Aur Pyaar Ho Gaya  (1997)  147 min
6                           ...Yahaan  (2005)  142 min
8                  ?: A Question Mark  (2012)   82 min

                       Genre  Rating  Votes        Director          Actor 1  \
1                      Drama     7.0      8   Gaurav Bakshi     Rasika Dugal
3            Comedy, Romance     4.4     35      Ovais Khan          Prateik
5     Comedy, Drama, Musical     4.7    827    Rahul Rawail       Bobby Deol
6        Drama, Romance, War     7.4  1,086  Shoojit Sircar  Jimmy Sheirgill
8  Horror, Mystery, Thriller     5.6    326   Allyson Patel        Yash Dave

                  Actor 2          Actor 3  \
1          Vivek Ghamande    Arvind Jangid
3              Ishita Raj  Siddhant Kapoor
5  Aishwarya Rai Bachchan    Shammi Kapoor
6          Minissha Lamba   Yashpal Sharma
8          Muntazir Ahmad     Kiran Bhatia

  Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3  \
1  #Gadhvi (He thought he was Gandhi),(2019),109 ...
3  #Yaaram,(2019),110 min,"Comedy, Romance",4.4,3...
5  ...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, D...
6  ...Yahaan,(2005),142 min,"Drama, Romance, War"...
8  ?: A Question Mark,(2012),82 min,"Horror, Myst...

  Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1  #Gadhvi (He thought he was Gandhi),(2019),109 ...
3  #Yaaram,(2019),110 min,"Comedy, Romance",4.4,3...
5  ...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, D...
6  ...Yahaan,(2005),142 min,"Drama, Romance, War"...
8  ?: A Question Mark,(2012),82 min,"Horror, Myst...

In [32]:
df2.describe()

            Rating
count  5659.000000
mean      5.898533
std       1.381165
min       1.100000
25%       5.000000
50%       6.100000
75%       6.900000
max      10.000000

In [33]:
df2.isna().sum()

Name                                                                      9850
Year                                                                      9850
Duration                                                                  9850
Genre                                                                     9850
Rating                                                                    9850
Votes                                                                     9850
Director                                                                  9850
Actor 1                                                                   9850
Actor 2                                                                   9850
Actor 3                                                                   9850
Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3       0
Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3       0
dtype: int64

In [34]:
df_final=df2.dropna()

In [35]:
df_final.shape

(5659, 12)

In [38]:
# Check the columns of df_final
print(df_final.columns)

# Ensure 'Gender' column is present and strip any unwanted spaces
df_final.columns = df_final.columns.str.strip()

# If 'Gender' exists, proceed with the countplot
if 'Gender' in df_final.columns:
    sns.countplot(x='Gender', hue='Ratings', data=df_final)
    plt.show()
else:
    print("The 'Gender' column is missing or misnamed.")

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3'],
      dtype='object')
The 'Gender' column is missing or misnamed.

In [40]:
# Check the columns of df_final
print(df_final.columns)

# Ensure 'Age' column is present and strip any unwanted spaces
df_final.columns = df_final.columns.str.strip()

# If 'Age' exists, plot the histogram
if 'Age' in df_final.columns:
    df_final['Age'].plot.hist(bins=25)
    plt.ylabel("Frequency")  # Rename y-axis to "Frequency"
    plt.xlabel("Age")
    plt.title("Distribution of Age")
    plt.show()
else:
    print("The 'Age' column is missing or misnamed.")

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3'],
      dtype='object')
The 'Age' column is missing or misnamed.

In [42]:
# Check the columns of df_final
print(df_final.columns)

# Remove leading/trailing spaces from column names
df_final.columns = df_final.columns.str.strip()

# Verify if the 'Ratings' column exists, and then plot
if 'Ratings' in df_final.columns:
    df_final['Ratings'].value_counts().plot(kind='bar')
    plt.xlabel("Ratings")
    plt.ylabel("Count")
    plt.title("Distribution of Ratings")
    plt.show()
else:
    print("The 'Ratings' column is missing or misnamed.")

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3',
       'Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3'],
      dtype='object')
The 'Ratings' column is missing or misnamed.

In [50]:

df_final.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,"Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3","Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3"
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,"#Gadhvi (He thought he was Gandhi),(2019),109 ...","#Gadhvi (He thought he was Gandhi),(2019),109 ..."
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,"#Yaaram,(2019),110 min,""Comedy, Romance"",4.4,3...","#Yaaram,(2019),110 min,""Comedy, Romance"",4.4,3..."
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,"...Aur Pyaar Ho Gaya,(1997),147 min,""Comedy, D...","...Aur Pyaar Ho Gaya,(1997),147 min,""Comedy, D..."
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,"...Yahaan,(2005),142 min,""Drama, Romance, War""...","...Yahaan,(2005),142 min,""Drama, Romance, War""..."
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,"?: A Question Mark,(2012),82 min,""Horror, Myst...","?: A Question Mark,(2012),82 min,""Horror, Myst..."

In [58]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Let's assume you want to scale numeric columns of df_final
numeric_cols = df_final.select_dtypes(include=['int64', 'float64'])

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(numeric_cols)

scaled_df = pd.DataFrame(scaled_data, columns=numeric_cols.columns)
scaled_df.head()

     Rating
0  0.662921
1  0.370787
2  0.404494
3  0.707865
4  0.505618